### ISSUE TITLE
Mobile?

### ISSUE THREAD

**Issue by Sempyos** [Pointifix/EvictionToolkit#1]
Make it work for mobile players too?

**Comment by Pointifix** [comment]
unfortunatly, i am not planning to, especially not the mod that adds a lot of UI elements, mobile wont have space for that anyways.

But i saw you have made some mods as well you might easily be able to make the second mod work on mobile, mail problem is changing hard coded keybindings to probably some UI button on mobile?

**Comment by Sempyos** [comment]
I can recommend some mods that have added folded buttons or windows :
https://github.com/Mnemotechnician/calculus
https://github.com/Mnemotechnician
This modder has mobile ui

**Comment by Pointifix** [comment]
Feel free to fork and adapt them to your liking
